export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

export const LOAD_HOTELS_SUCCESS = 'LOAD_HOTELS_SUCCESS';

export const SET_FILTER_VALUE = 'SET_FILTER_VALUE';